services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foodplanner_ai
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: